### ISSUE TITLE
Storybook not launching

### ISSUE THREAD

**Issue by souhailmerroun** [Blazity/next-enterprise#39] opened 2023-05-24 16:26 UTC
<img width="652" alt="image" src="https://github.com/Blazity/next-enterprise/assets/8895242/618c6795-8520-4d51-ae81-9a550768de7f">

//

i've tested on a freshly created codespace from main.

**Comment by bmstefanski** [comment] 2023-05-24 16:55
Thanks for reporting this. I can't reproduce it on macos, are you on linux/windows? WSL? `code 137` sounds like an issue with RAM?

**Comment by souhailmerroun** [comment] 2023-05-24 17:15
No it was on a freshly created Codespace. 

<img width="889" alt="image" src="https://github.com/Blazity/next-enterprise/assets/8895242/888a7299-78ac-4af8-a72b-78515b5e3d98">



I will re-test on another one that is 4-core or more.

**Comment by bmstefanski** [comment] 2023-05-30 12:13
@souhailmerroun closing this now since I couldnt reproduce. If you're still getting the error please let me know

**Closed by bmstefanski** 2023-05-30 12:13 UTC
