### ISSUE TITLE
Suggestion: App router Version

### ISSUE THREAD

**Issue by theodesp** [Blazity/next-enterprise#37] opened 2023-05-24 09:47 UTC
Nice Project here.

It would be awesome if you have a version with the new App router and Server Side Components since it's more stable now.

Thank you.

**Comment by Nilmanduil** [comment] 2023-05-24 13:52
Hello, it seems to be a duplicate of #32

**Comment by bmstefanski** [comment] 2023-05-24 17:14
Hi, thank you! Answering the question, yes, we will convert pages router to App Dir! You can follow #32 to keep getting updated.

**Closed** 2023-05-24 17:14 UTC
